apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: ClickHouse
    orgId: 1
  - name: Loki
    orgId: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 5s
      httpMethod: POST

  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    editable: false
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      username: observer
      defaultDatabase: perfmon
      tlsSkipVerify: false
    secureJsonData:
      password: observer

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      maxLines: 1000
